# Generated by Django 4.1.2 on 2022-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='client_note',
            field=models.CharField(blank=True, max_length=255, verbose_name="Client's note"),
        ),
    ]
